"use client";
import Link from "next/link";
import { ArrowUpRight, ShieldCheck, Users } from "lucide-react";
import { useScope } from "./queries";
export function Overview() {
  const { activeWorkspace, user, href } = useScope();
  const resident = activeWorkspace?.type === "resident"; const operator = activeWorkspace?.type === "guard" || activeWorkspace?.type === "security";
  return <div className="space-y-6"><section className="rounded-2xl bg-foreground p-7 text-card sm:p-10"><p className="text-xs font-semibold uppercase tracking-widest text-primary">{activeWorkspace?.label}</p><h2 className="mt-4 text-3xl font-bold tracking-tight">Welcome{user.firstName ? `, ${user.firstName}` : " back"}.</h2><p className="mt-3 max-w-lg text-sm leading-6 text-card/70">{resident ? "A familiar face or a first visit. Make every arrival a little easier." : "Keep your community moving safely. Your access workspace is ready."}</p></section><div className="grid gap-5 sm:grid-cols-2">{resident && <Shortcut href={href("/visitors")} title="My visitors" description="Create invitations, share passes, and manage upcoming visits." />}{operator && <Shortcut href={href("/gate")} title="Live Gate" description="Verify arrivals and record check-ins and departures." />}{activeWorkspace?.type !== "organization" && !resident && <Shortcut href={href("/access")} title="On-site & activity" description="See who’s inside and review the estate’s access history." />}{activeWorkspace?.type === "organization" && <section className="panel"><Users className="size-6 text-accent-foreground" /><h3 className="mt-4 font-bold">Organization workspace</h3><p className="mt-2 text-sm text-muted-foreground">Access management is available through your estate workspaces. Choose one from the workspace menu.</p></section>}</div></div>;
}
function Shortcut({ href, title, description }: { href: string; title: string; description: string }) { return <Link href={href} className="panel group block transition-colors hover:border-primary"><div className="flex items-center justify-between"><ShieldCheck className="size-6 text-accent-foreground" /><ArrowUpRight className="size-5 text-muted-foreground" /></div><h3 className="mt-6 text-lg font-bold">{title}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{description}</p></Link>; }
