"use client";
import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { QRCodeSVG } from "qrcode.react";
import { Button } from "@/components/ui/button";
import { api } from "@/lib/api/client";
import { queryKeys, useScope } from "./queries";
import type { Invitation, Pass } from "./types";
import { date, ErrorNotice, InvitationBadges, Loading, PreviewNotice, Status } from "./ui";
export function VisitorDetail({ id }: { id: string }) {
  const { base, estate, userId, enabled, preview } = useScope(); const client = useQueryClient();
  const [confirm, setConfirm] = useState(false); const [copied, setCopied] = useState("");
  const path = `${base}/visitor-invitations/${encodeURIComponent(id)}`;
  const invitation = useQuery({ queryKey: queryKeys.detail(userId, estate, id), queryFn: ({ signal }) => api<Invitation>(path, { signal }), enabled, refetchInterval: 15_000 });
  const pass = useQuery({ queryKey: queryKeys.pass(userId, estate, id), queryFn: ({ signal }) => api<Pass>(`${path}/pass`, { signal }), enabled, refetchInterval: 30_000 });
  const cancel = useMutation({ mutationFn: () => api(path + "/cancel", { method: "PATCH" }), onSuccess: async () => { setConfirm(false); await client.invalidateQueries({ queryKey: queryKeys.invitations(userId, estate) }); } });
  if (preview) return <PreviewNotice />;
  const visitor = invitation.data;
  return <div><ErrorNotice error={invitation.error} retry={() => void invitation.refetch()} />{invitation.isPending ? <Loading /> : visitor && <div className="grid gap-6 lg:grid-cols-[1fr_360px]"><section className="panel"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-2xl font-bold">{visitor.visitorFirstName} {visitor.visitorLastName}</h2><InvitationBadges visitStatus={visitor.visitStatus} status={visitor.status} /></div><dl className="mt-8 grid gap-6 text-sm sm:grid-cols-2">{[["Hosting unit", visitor.hostResidency.unit.code], ["Phone", visitor.visitorPhone || "Not provided"], ["Valid from", date(visitor.validFrom)], ["Valid until", date(visitor.validUntil)], ["Purpose", visitor.purpose || "Not specified"]].map(([label, value]) => <div key={label}><dt className="text-muted-foreground">{label}</dt><dd className="mt-1 font-semibold">{value}</dd></div>)}</dl>{["PENDING", "ACTIVE"].includes(visitor.status) && <div className="mt-8 border-t pt-6">{confirm ? <div><p className="mb-3 text-sm">Cancel this invitation? Its pass will no longer allow entry.</p><div className="flex gap-3"><Button variant="destructive" isDisabled={cancel.isPending} onPress={() => cancel.mutate()}>{cancel.isPending ? "Cancelling…" : "Yes, cancel invitation"}</Button><Button variant="outline" isDisabled={cancel.isPending} onPress={() => setConfirm(false)}>Keep invitation</Button></div></div> : <Button variant="destructive" onPress={() => setConfirm(true)}>Cancel invitation</Button>}<ErrorNotice error={cancel.error} /></div>}</section><section className="panel text-center"><p className="text-xs font-bold uppercase tracking-widest text-accent-foreground">Visitor access pass</p><ErrorNotice error={pass.error} retry={() => void pass.refetch()} />{pass.isPending ? <Loading /> : pass.data && <><div className="mt-4"><Status value={pass.data.effectiveStatus || pass.data.status} /></div>{pass.data.token && <div className="mx-auto my-6 w-fit rounded-xl border bg-white p-4"><QRCodeSVG value={pass.data.token} size={200} title="Visitor access credential" /></div>}<p className="mt-5 font-mono text-3xl font-bold tracking-[0.2em]">{pass.data.code}</p><p className="mt-3 text-xs leading-5 text-muted-foreground">Share this code with your visitor to present at the gate.<br />Valid until {date(pass.data.validUntil)}</p><Button variant="outline" className="mt-5" onPress={async () => { try { await navigator.clipboard.writeText(pass.data!.code); setCopied("Code copied."); } catch { setCopied("Couldn’t copy. Select the code above to copy it manually."); } }}>Copy code</Button><p role="status" className="mt-3 text-xs">{copied}</p></>}</section></div>}</div>;
}
